### PR TITLE
fix: typo in Chapter 2

### PR DESCRIPTION
**Pull request by phaleth**

### CODE REVIEW

**Comment by skylee03** [comment]
LGTM! I will fix them as soon as possible. If you have any other feedback, please let us know!

**Comment by skylee03** [comment]
I noticed that you opened a PR for each typo, so I'll merge them to avoid cluttering the git log.

**Comment by phaleth** [comment]
yeah, I keep opening new PRs, cause I'm not sure you gonna apply each and every of those changes

feel free to close the other ones

**Comment by skylee03** [comment]
> yeah, I keep opening new PRs, cause I'm not sure you gonna apply each and every of those changes
> 
> feel free to close the other ones

Let me know when you're done. Thanks!

**Review by skylee03 — APPROVED** [review]
LGTM! Thank you for your contribution.
I will merge these changes now. If you have other changes later, please feel free to open a new PR.

**Pull request merged**
